### PR TITLE
fix wallets page

### PR DESCRIPTION
**Pull request by nylira**
- [x] alphabetize wallets
- [x] hide inactive wallets
- [x] categorize wallets into web, ios, android

Preview:
image

### CODE REVIEW

**Comment by nylira** [comment]
- [x] show only active apps on ecosystem page

**Review by lovincyrus — APPROVED** [review]
lgtm

**Comment by nassdonald** [comment]
Woo! As agreed, I'm going to merge my changes with this.

**Comment by nylira** [comment]
Let’s merge this. Nass’s changes can come in a future PR.

**Pull request merged**
