### PR TITLE
peng/fix roadmap loading 

### PR DESCRIPTION
**Pull request by nylira**
- [x] fix issue where roadmap logos were not loading in time for the interconnected nodes

This is not an ideal fix because it involves a number of hard coded heights. But it'll work for our purposes.

### CODE REVIEW

**Comment by faboweb** [comment]
Why does this fix a loading issue?

**Comment by nylira** [comment]
Many times, the roadmap loads the content from the GitHub api before the images finish loading. The cross-project connection lines are drawn, but they're out of the place after the images load. This happens to me (and others have brought this up) about 1/3 of the time.  @zramsay 

## Before

roadmap-bug

## After

roadmap-unbugged

**Comment by faboweb** [comment]
Can we load the github content or draw the lines after the `img.onload`s are called?

**Comment by nylira** [comment]
@faboweb that's a better idea :) Just implemented a version of this where the app watches for the nodes and images to be loaded before drawing the lines.

**Pull request merged**
