### PR TITLE
new Ecosystem page

### PR DESCRIPTION
**Pull request by lovincyrus**
Preview: https://deploy-preview-85--cosmos-network.netlify.app/ecosystem

- [x] responsive layout
- [x] tweak checkbox
- [x] apply .sr-only in checkbox
- [x] UI change maybe
- [x] CTA section, vertically space out columns more on mobile, and make sure they’re all aligned left
- [x] clean up the '?' apps
- [x] style search
- [x] style pagination
- [x] uncategorized and unknown categories should be at the bottom of filters
- [x] ~~minify algolia.css, tooltip.css~~
- [x] ~~average color list item bg color~~
- [x] update beta, alpha dot color
- [x] ~~sync up algolia csv/api to algolia index~~
- [x] start by alphabetical order (ranking and sorting on algolia)
- [x] add a banner to `Built with the Cosmos SDK`'s section on `/sdk`
- [ ] 🚢

Related: https://github.com/allinbits/design/issues/6

### CODE REVIEW

**Comment by nassdonald** [comment]
@lovincyrus, just a small request for tweaks on the thumbnail element:

- [ ] Reduce opacity of blurred img to `opacity 0.7` and increase scale to `transform scale(2.3)`.
- [ ] Change gradient on parent image container to `linear-gradient(135deg,#fff,#e0e0e0)`.

**Comment by lovincyrus** [comment]
Ready for review. @nassdonald

**Review by nassdonald — CHANGES_REQUESTED** [review]
- [ ] Sidebar items are still jumping around when you select some categories. Not sure if that's behavior that's baked into Algolia or not? Seems to be when the count is the same for a few items in a row. I think a fixed order for the categories might help, if that's possible?
https://user-images.githubusercontent.com/2961244/103764636-bc60e700-5013-11eb-96a2-d8b47b37fd64.mov
- [ ] There's a strange layout case ~700-833px where the sidebar stacks above a two-col results grid. If anything, it should adapt sooner to the mobile filters layout to avoid that massive vertical space before the results.
- [ ] As mentioned before, the introduction of a background-color to the filters on mobile **shouldn't** override the active background-color (blue).
image
- [ ] On a similar note, the hover and focus states don't seem to be working on the Categories filters anymore. 😕 
- [ ] Not sure if it was clear when we last discussed, but the counter in the title "(X)" was only to be added if it was possible to update the title with the selected category. For instance, if you select Finance category, it would update to "Finance (53)". If you then revert to showing all apps, it should read (by default) "Cosmos apps and projects" with no counter. We should style the counter better than "(X)" - maybe `float right`, no parenthesis, and `--dim` color - but not high priority.
- [ ] The `.text__category` element in the results is meant to be `--dim` color.
- [ ] The title `.text__top__name__none` should use a variable too: `--txt`.
- [ ] The bottom CTA section should have a background-color `--app-fg`, and the buttons should have no background color - which you can maybe just remove in the component itself (for outline style buttons only).
- [ ] The min-height should be removed from the bottom CTA section and flexbox should be used to ensure the cols are all equal height and buttons are aligned to the bottom of the cell. Right now the titles wrap and get too close to the buttons. Hit me up if you're not sure how to achieve this. 🙂 
image

**Review by nassdonald — DISMISSED** [review]
Just a few minor bugs lingering and we're good.

- [x] Hover state on Categories still not working
- [x] Background color of filters on mobile and `.faq` panel should both use variable `--app-fg`
- [x] `.layout__sidebar` margin-right should be `-1rem` on stacked mobile layout.
- [x] `.faq` panel should have a max-width of `24rem`.
- [x] `.text__top__name__none` should reduce in font-size on mobile with the other titles.
image
- [x] To prevent weird wrapping of status dots in titles (pictured above), the width of `.ais-Hits-item` should be 100%, rather than `min-content`.
- [x] Increase the title size to `1rem` but keep the category subtitle at `0.75rem` on mobile. Also, don't reduce the size of the icons, because they become too small. I know it doesn't look as good, but the usability is better. We'll improve the sizing and spacing later. Here's a quick tweak in-browser:
image

**Comment by lovincyrus** [comment]
Ready to 🚢

**Review by nassdonald — APPROVED** [review]
Few minor things to fix, but let's ship and fix later.

**Pull request merged**
