### PR TITLE
peng/revamp navigation

### PR DESCRIPTION
**Pull request by nylira**
Based on feedback from members of the team, we need to make the FAQ and Whitepaper easier to find. Both of these items need to be on the main navigation.

- [x] make it easier to find whitepaper/FAQ - `when ico?` `where can I buy atoms` `launch delayed again?`
- [x] move security page to tendermint only
- [x] remove nested about section in favor of main links
- [x] allow downloading pdf of whitepaper and fix OverlayBtn icons
- [x] updated redirects, people can now visit https://cosmos.network/telegram to get to our telegram and https://cosmos.network/riot or https://cosmos.network/matrix to get to our riot

I'm thinking that we can remove the main GitHub link (in favor of people visiting the Developers page) and move Security to a Developers sub-page.

### CODE REVIEW

**Comment by nylira** [comment]
### Old Nav
Impossible to find FAQ and Whitepaper

screen shot 2018-03-06 at 12 55 54 pm

### New Nav
Easier!

screen shot 2018-03-06 at 12 55 59 pm

**Comment by nylira** [comment]
### whitepaper before
Broken icons, no download link

screen shot 2018-03-06 at 1 08 46 pm


### whitepaper after
screen shot 2018-03-06 at 1 04 07 pm

**Comment by faboweb** [comment]
I have the feeling the navigation bar gets pretty crowded, but you guys know best.

**Comment by nylira** [comment]
@faboweb simplification is in progress, right now though it's best to have everything up top. Can you approve it?

**Pull request merged**
