### PR TITLE
fix: Update video on the starport page

### PR DESCRIPTION
**Pull request by fadeev**
Updated the video to the [latest one](https://www.youtube.com/watch?v=5RqAIE0b8Kw). We probably need a better cover image for this.

### CODE REVIEW

**Comment by lovincyrus** [comment]
> We probably need a better cover image for this.

cc: @miguel-tendermint

**Comment by miguel-tendermint** [comment]
How would [something like this](https://www.figma.com/file/jwsszv5yFMnIj12Vry8E75/cosmos.network-2021?node-id=3160%3A9189) work folks?

**Comment by lovincyrus** [comment]
> How would [something like this](https://www.figma.com/file/jwsszv5yFMnIj12Vry8E75/cosmos.network-2021?node-id=3160%3A9189) work folks?

works for me. You good with this? @fadeev

**Comment by fadeev** [comment]
Well, it's not about launching a blockchain, but more about introducing people to Starport.

**Comment by miguel-tendermint** [comment]
Ohh gotcha @fadeev !
How about something like this instead?

thumbnail

**Comment by fadeev** [comment]
@miguel-tendermint great! Let's go with that.

**Comment by lovincyrus** [comment]
Starport Intro video will be updated in this PR https://github.com/cosmos/cosmos.network/pull/135 instead.

**Pull request closed without merging**
