### PR TITLE
Add multi step forms for newsletter signup

### PR DESCRIPTION
**Pull request by lovincyrus**
ref: https://github.com/cosmos/cosmos.network/issues/122

Screen Shot 2021-04-28 at 17 04 29
Screen Shot 2021-04-28 at 17 04 39
Screen Shot 2021-04-28 at 17 04 50

### CODE REVIEW

**Comment by miguel-tendermint** [comment]
Hey @lovincyrus,
Few comments that i wanted to run by you:

- Is it possible to condense the layout on desktop to a total of 8 cols, 4 cols for each content block?
- Can we try to smooth the transition between the first and second steps? looks a little bit weird at the moment, maybe switching to the 8 cols will help, as the form will take up the same cols on all steps.
- On the second step we seem to have a bit more padding on the right side, when compared to the left side, can we make it the same all the way around?
- we also seem to be missing a bottom horizontal divider, you can see it better [here](https://www.figma.com/file/jwsszv5yFMnIj12Vry8E75/cosmos.network-2021?node-id=2997%3A22777), in context

Thank Cyrus!

**Review by miguel-tendermint — CHANGES_REQUESTED** [review]
Hey @lovincyrus,
Few comments that i wanted to run by you:

- [ ] Is it possible to condense the layout on desktop to a total of 8 cols, 4 cols for each content block?
- [ ] Can we try to smooth the transition between the first and second steps? looks a little bit weird at the moment, maybe switching to the 8 cols will help, as the form will take up the same cols on all steps.
- [ ] On the second step we seem to have a bit more padding on the right side, when compared to the left side, can we make it the same all the way around?
- [ ] we also seem to be missing a bottom horizontal divider, you can see it better [here](https://www.figma.com/file/jwsszv5yFMnIj12Vry8E75/cosmos.network-2021?node-id=2997%3A22777), in context

Thank Cyrus!

**Comment by lovincyrus** [comment]
Nice catch! @miguel-tendermint 

- Added horizontal divider
- Added columns for the form. This fixes all the weird transition issues.

**Comment by miguel-tendermint** [comment]
@lovincyrus we still have a little bit of a jump in between steps, but I think that's something we can work on after we push this initial version, let's get people signing up again while we work on it! 

Video attached, may be easier to understand, much more noticeable between first and second steps where we can still see the cols adjusting, the last step is a bit abrupt but no weird nudging going on 

https://user-images.githubusercontent.com/76948640/116666775-48b46280-a993-11eb-88dc-fddb3ca850cd.mov

Thanks Cyrus

**Review by miguel-tendermint — APPROVED** [review]

**Pull request merged**
